### ISSUE TITLE
Vs code can not find hx711_noblock.pio.h

### ISSUE THREAD

**Issue by Chrisx43** [endail/pico-scale#6]
After cloning the repository using method 1. It is not possibile for me to build or run CTest. VsCode can not find the header file hx711_noblock.pio.h. 
It is not in "extern/hx711-pico-c/include/hx711_noblock.pio.h" after cloning the repository

**Comment by ali1234** [comment]
run `git submodule update --init`

**Comment by endail** [comment]
I haven't updated this repo since I updated the hx711-pico-c repo. Unfortunately that means it's trying to include hx711_noblock.pio.h which doesn't exist any more. I'm working on making pico-scale ADC agnostic so that it doesn't specifically require a HX711 to work.

In the meantime, you could point the submodule within pico-scale to [hx711-pico-c@v1](https://github.com/endail/hx711-pico-c/tree/v1) which does include hx711_noblock.pio.h.

**Comment by endail** [comment]
Fixed in https://github.com/endail/pico-scale/tree/abstraction

Will merge into main soon after some testing.
